export const OFFICIAL_ENGLISH_SET_DEFS = [
  { label: "Base Set", era: "Base Era", aliases: ["Base Set Unlimited", "Base Set Shadowless", "Base Set 1st Edition", "Base Set"] },
  { label: "Jungle", era: "Base Era", aliases: ["Jungle", "Jungle 1st Edition"] },
  { label: "Fossil", era: "Base Era", aliases: ["Fossil", "Fossil 1st Edition"] },
  { label: "Base Set 2", era: "Base Era", aliases: ["Base Set 2"] },
  { label: "Team Rocket", era: "Base Era", aliases: ["Team Rocket", "Team Rocket 1st Edition"] },
  { label: "Gym Heroes", era: "Base Era", aliases: ["Gym Heroes", "Gym Heroes 1st Edition"] },
  { label: "Gym Challenge", era: "Base Era", aliases: ["Gym Challenge", "Gym Challenge 1st Edition"] },
  { label: "Neo Genesis", era: "Neo Era", aliases: ["Neo Genesis", "Neo Genesis 1st Edition"] },
  { label: "Neo Discovery", era: "Neo Era", aliases: ["Neo Discovery", "Neo Discovery 1st Edition"] },
  { label: "Neo Revelation", era: "Neo Era", aliases: ["Neo Revelation", "Neo Revelation 1st Edition"] },
  { label: "Neo Destiny", era: "Neo Era", aliases: ["Neo Destiny", "Neo Destiny 1st Edition"] },
  { label: "Legendary Collection", era: "Neo Era", aliases: ["Legendary Collection"] },
  { label: "Expedition Base Set", era: "e-Card Era", aliases: ["Expedition", "Expedition Base Set"] },
  { label: "Aquapolis", era: "e-Card Era", aliases: ["Aquapolis"] },
  { label: "Skyridge", era: "e-Card Era", aliases: ["Skyridge"] },
  { label: "EX Ruby & Sapphire", era: "EX Series", aliases: ["Ruby and Sapphire", "Ruby And Sapphire", "EX Ruby & Sapphire"] },
  { label: "EX Sandstorm", era: "EX Series", aliases: ["Sandstorm", "EX Sandstorm"] },
  { label: "EX Dragon", era: "EX Series", aliases: ["Dragon", "EX Dragon"] },
  { label: "EX Team Magma vs Team Aqua", era: "EX Series", aliases: ["Team Magma vs Team Aqua", "EX Team Magma vs Team Aqua"] },
  { label: "EX Hidden Legends", era: "EX Series", aliases: ["Hidden Legends", "EX Hidden Legends"] },
  { label: "EX FireRed & LeafGreen", era: "EX Series", aliases: ["Fire Red Leaf Green", "FireRed LeafGreen", "EX FireRed & LeafGreen"] },
  { label: "EX Team Rocket Returns", era: "EX Series", aliases: ["Team Rocket Returns", "EX Team Rocket Returns"] },
  { label: "EX Deoxys", era: "EX Series", aliases: ["Deoxys", "EX Deoxys"] },
  { label: "EX Emerald", era: "EX Series", aliases: ["Emerald", "EX Emerald"] },
  { label: "EX Unseen Forces", era: "EX Series", aliases: ["Unseen Forces", "EX Unseen Forces"] },
  { label: "EX Delta Species", era: "EX Series", aliases: ["Delta Species", "EX Delta Species"] },
  { label: "EX Legend Maker", era: "EX Series", aliases: ["Legend Maker", "EX Legend Maker"] },
  { label: "EX Holon Phantoms", era: "EX Series", aliases: ["Holon Phantoms", "EX Holon Phantoms"] },
  { label: "EX Crystal Guardians", era: "EX Series", aliases: ["Crystal Guardians", "EX Crystal Guardians"] },
  { label: "EX Dragon Frontiers", era: "EX Series", aliases: ["Dragon Frontiers", "EX Dragon Frontiers"] },
  { label: "EX Power Keepers", era: "EX Series", aliases: ["Power Keepers", "EX Power Keepers"] },
  { label: "Diamond & Pearl", era: "EX Series", aliases: ["Diamond & Pearl", "Diamond And Pearl"] },
  { label: "DP Mysterious Treasures", era: "Diamond & Pearl Series", aliases: ["Mysterious Treasures", "DP Mysterious Treasures"] },
  { label: "DP Secret Wonders", era: "Diamond & Pearl Series", aliases: ["Secret Wonders", "DP Secret Wonders"] },
  { label: "DP Great Encounters", era: "Diamond & Pearl Series", aliases: ["Great Encounters", "DP Great Encounters"] },
  { label: "DP Majestic Dawn", era: "Diamond & Pearl Series", aliases: ["Majestic Dawn", "DP Majestic Dawn"] },
  { label: "DP Legends Awakened", era: "Diamond & Pearl Series", aliases: ["Legends Awakened", "DP Legends Awakened"] },
  { label: "DP Stormfront", era: "Diamond & Pearl Series", aliases: ["Stormfront", "DP Stormfront"] },
  { label: "Platinum", era: "Diamond & Pearl Series", aliases: ["Platinum"] },
  { label: "Platinum Rising Rivals", era: "Platinum Series", aliases: ["Rising Rivals", "Platinum Rising Rivals"] },
  { label: "Platinum Supreme Victors", era: "Platinum Series", aliases: ["Supreme Victors", "Platinum Supreme Victors"] },
  { label: "Platinum Arceus", era: "Platinum Series", aliases: ["Arceus", "Platinum Arceus"] },
  { label: "HeartGold & SoulSilver", era: "Platinum Series", aliases: ["HeartGold SoulSilver", "HeartGold & SoulSilver"] },
  { label: "HGSS Unleashed", era: "HeartGold & SoulSilver Series", aliases: ["Unleashed", "HGSS Unleashed"] },
  { label: "HGSS Undaunted", era: "HeartGold & SoulSilver Series", aliases: ["Undaunted", "HGSS Undaunted"] },
  { label: "HGSS Triumphant", era: "HeartGold & SoulSilver Series", aliases: ["Triumphant", "HGSS Triumphant"] },
  { label: "Call of Legends", era: "HeartGold & SoulSilver Series", aliases: ["Call of Legends"] },
  { label: "Black & White", era: "HeartGold & SoulSilver Series", aliases: ["Black and White", "Black And White", "Black & White"] },
  { label: "BW Emerging Powers", era: "Black & White Series", aliases: ["Emerging Powers", "BW Emerging Powers"] },
  { label: "BW Noble Victories", era: "Black & White Series", aliases: ["Noble Victories", "BW Noble Victories"] },
  { label: "BW Next Destinies", era: "Black & White Series", aliases: ["Next Destinies", "BW Next Destinies"] },
  { label: "BW Dark Explorers", era: "Black & White Series", aliases: ["Dark Explorers", "BW Dark Explorers"] },
  { label: "BW Dragons Exalted", era: "Black & White Series", aliases: ["Dragons Exalted", "BW Dragons Exalted"] },
  { label: "BW Boundaries Crossed", era: "Black & White Series", aliases: ["Boundaries Crossed", "BW Boundaries Crossed"] },
  { label: "BW Plasma Storm", era: "Black & White Series", aliases: ["Plasma Storm", "BW Plasma Storm"] },
  { label: "BW Plasma Freeze", era: "Black & White Series", aliases: ["Plasma Freeze", "BW Plasma Freeze"] },
  { label: "BW Plasma Blast", era: "Black & White Series", aliases: ["Plasma Blast", "BW Plasma Blast"] },
  { label: "BW Legendary Treasures", era: "Black & White Series", aliases: ["Legendary Treasures", "BW Legendary Treasures"] },
  { label: "XY", era: "Black & White Series", aliases: ["XY Base", "XY"] },
  { label: "XY Flashfire", era: "XY Series", aliases: ["Flashfire", "XY Flashfire"] },
  { label: "XY Furious Fists", era: "XY Series", aliases: ["Furious Fists", "XY Furious Fists"] },
  { label: "XY Phantom Forces", era: "XY Series", aliases: ["Phantom Forces", "XY Phantom Forces"] },
  { label: "XY Primal Clash", era: "XY Series", aliases: ["Primal Clash", "XY Primal Clash"] },
  { label: "XY Roaring Skies", era: "XY Series", aliases: ["Roaring Skies", "XY Roaring Skies"] },
  { label: "XY Ancient Origins", era: "XY Series", aliases: ["Ancient Origins", "XY Ancient Origins"] },
  { label: "XY BREAKthrough", era: "XY Series", aliases: ["BREAKthrough", "Breakthrough", "XY BREAKthrough"] },
  { label: "XY BREAKpoint", era: "XY Series", aliases: ["BREAKpoint", "Breakpoint", "XY BREAKpoint"] },
  { label: "Generations", era: "XY Series", aliases: ["Generations"] },
  { label: "XY Fates Collide", era: "XY Series", aliases: ["Fates Collide", "XY Fates Collide"] },
  { label: "XY Steam Siege", era: "XY Series", aliases: ["Steam Siege", "XY Steam Siege"] },
  { label: "XY Evolutions", era: "XY Series", aliases: ["Evolutions", "XY Evolutions"] },
  { label: "Sun & Moon", era: "XY Series", aliases: ["Sun & Moon", "Sun And Moon"] },
  { label: "SM Guardians Rising", era: "Sun & Moon Series", aliases: ["Guardians Rising", "SM Guardians Rising"] },
  { label: "SM Burning Shadows", era: "Sun & Moon Series", aliases: ["Burning Shadows", "SM Burning Shadows"] },
  { label: "Shining Legends", era: "Sun & Moon Series", aliases: ["Shining Legends"] },
  { label: "SM Crimson Invasion", era: "Sun & Moon Series", aliases: ["Crimson Invasion", "SM Crimson Invasion"] },
  { label: "SM Ultra Prism", era: "Sun & Moon Series", aliases: ["Ultra Prism", "SM Ultra Prism"] },
  { label: "SM Forbidden Light", era: "Sun & Moon Series", aliases: ["Forbidden Light", "SM Forbidden Light"] },
  { label: "SM Celestial Storm", era: "Sun & Moon Series", aliases: ["Celestial Storm", "SM Celestial Storm"] },
  { label: "Dragon Majesty", era: "Sun & Moon Series", aliases: ["Dragon Majesty"] },
  { label: "SM Lost Thunder", era: "Sun & Moon Series", aliases: ["Lost Thunder", "SM Lost Thunder"] },
  { label: "SM Team Up", era: "Sun & Moon Series", aliases: ["Team Up", "SM Team Up"] },
  { label: "Detective Pikachu", era: "Sun & Moon Series", aliases: ["Detective Pikachu"] },
  { label: "SM Unbroken Bonds", era: "Sun & Moon Series", aliases: ["Unbroken Bonds", "SM Unbroken Bonds"] },
  { label: "SM Unified Minds", era: "Sun & Moon Series", aliases: ["Unified Minds", "SM Unified Minds"] },
  { label: "Hidden Fates", era: "Sun & Moon Series", aliases: ["Hidden Fates"] },
  { label: "SM Cosmic Eclipse", era: "Sun & Moon Series", aliases: ["Cosmic Eclipse", "SM Cosmic Eclipse"] },
  { label: "Sword & Shield", era: "Sun & Moon Series", aliases: ["Sword & Shield", "Sword And Shield"] },
  { label: "SWSH Rebel Clash", era: "Sword & Shield Series", aliases: ["Rebel Clash", "SWSH Rebel Clash"] },
  { label: "SWSH Darkness Blaze", era: "Sword & Shield Series", aliases: ["Darkness Ablaze", "SWSH Darkness Blaze"] },
  { label: "Champion's Path", era: "Sword & Shield Series", aliases: ["Champion's Path", "Champions Path"] },
  { label: "SWSH Vivid Voltage", era: "Sword & Shield Series", aliases: ["Vivid Voltage", "SWSH Vivid Voltage"] },
  { label: "Shining Fates", era: "Sword & Shield Series", aliases: ["Shining Fates"] },
  { label: "SWSH Battle Styles", era: "Sword & Shield Series", aliases: ["Battle Styles", "SWSH Battle Styles"] },
  { label: "SWSH Chilling Reign", era: "Sword & Shield Series", aliases: ["Chilling Reign", "SWSH Chilling Reign"] },
  { label: "SWSH Evolving Skies", era: "Sword & Shield Series", aliases: ["Evolving Skies", "SWSH Evolving Skies"] },
  { label: "Celebrations", era: "Sword & Shield Series", aliases: ["Celebrations"] },
  { label: "SWSH Fusion Strike", era: "Sword & Shield Series", aliases: ["Fusion Strike", "SWSH Fusion Strike"] },
  { label: "SWSH Brilliant Stars", era: "Sword & Shield Series", aliases: ["Brilliant Stars", "SWSH Brilliant Stars"] },
  { label: "SWSH Astral Radiance", era: "Sword & Shield Series", aliases: ["Astral Radiance", "SWSH Astral Radiance"] },
  { label: "Pokémon GO", era: "Sword & Shield Series", aliases: ["Pokemon GO", "Pokemon Go", "Pokémon GO"] },
  { label: "SWSH Lost Origin", era: "Sword & Shield Series", aliases: ["Lost Origin", "SWSH Lost Origin"] },
  { label: "SWSH Silver Tempest", era: "Sword & Shield Series", aliases: ["Silver Tempest", "SWSH Silver Tempest"] },
  { label: "Crown Zenith", era: "Sword & Shield Series", aliases: ["Crown Zenith"] },
  { label: "Scarlet & Violet", era: "Sword & Shield Series", aliases: ["Scarlet & Violet", "Scarlet And Violet", "Scarlet & Violet Base", "Scarlet And Violet Base"] },
  { label: "SV Paldea Evolved", era: "Sword & Shield Series", aliases: ["Paldea Evolved", "SV Paldea Evolved"] },
  { label: "SV Obsidian Flames", era: "Scarlet & Violet Series", aliases: ["Obsidian Flames", "SV Obsidian Flames"] },
  { label: "151", era: "Scarlet & Violet Series", aliases: ["Pokemon Card 151", "151"] },
  { label: "SV Paradox Rift", era: "Scarlet & Violet Series", aliases: ["Paradox Rift", "SV Paradox Rift"] },
  { label: "Paldean Fates", era: "Scarlet & Violet Series", aliases: ["Paldean Fates"] },
  { label: "SV Temporal Forces", era: "Scarlet & Violet Series", aliases: ["Temporal Forces", "SV Temporal Forces"] },
  { label: "SV Twilight Masquerade", era: "Scarlet & Violet Series", aliases: ["Twilight Masquerade", "SV Twilight Masquerade"] },
  { label: "Shrouded Fable", era: "Scarlet & Violet Series", aliases: ["Shrouded Fable"] },
  { label: "SV Stellar Crown", era: "Scarlet & Violet Series", aliases: ["Stellar Crown", "SV Stellar Crown"] },
  { label: "SV Surging Sparks", era: "Scarlet & Violet Series", aliases: ["Surging Sparks", "SV Surging Sparks"] },
  { label: "Prismatic Evolutions", era: "Scarlet & Violet Series", aliases: ["Prismatic Evolutions"] },
  { label: "Journey Together", era: "Scarlet & Violet Series", aliases: ["Journey Together"] },
  { label: "Destined Rivals", era: "Scarlet & Violet Series", aliases: ["Destined Rivals"] },
  { label: "Black Bolt", era: "Scarlet & Violet Series", aliases: ["Black Bolt"] },
  { label: "White Flare", era: "Scarlet & Violet Series", aliases: ["White Flare"] },
  { label: "Mega Evolution (Base)", era: "Scarlet & Violet Series", aliases: ["Mega Evolution"] },
  { label: "Phantasmal Flames", era: "Scarlet & Violet Series", aliases: ["Phantasmal Flames"] },
  { label: "Ascended Heroes", era: "Scarlet & Violet Series", aliases: ["Ascended Heroes"] },
];

export const OFFICIAL_JAPANESE_SET_DEFS = [
  { label: "Nihil Zero (m3)", era: "MEGA ERA", aliases: ["Nihil Zero", "Nihil Zero M3"] },
  { label: "Mega Dream (m2a)", era: "MEGA ERA", aliases: ["Mega Dream", "Mega Dream M2a"] },
  { label: "Inferno X (m2)", era: "MEGA ERA", aliases: ["Inferno X", "Inferno X M2"] },
  { label: "Mega Symphonia (m1S)", era: "MEGA ERA", aliases: ["Mega Symphonia", "Mega Symphonia M1s"] },
  { label: "Mega Brave (m1L)", era: "MEGA ERA", aliases: ["Mega Brave", "Mega Brave M1l"] },
  { label: "Black Bolt Japanese (sv11B)", era: "SCARLET & VIOLET ERA", aliases: ["Black Bolt Japanese", "Black Bolt"] },
  { label: "White Flare Japanese (sv11W)", era: "SCARLET & VIOLET ERA", aliases: ["White Flare Japanese", "White Flare"] },
  { label: "Glory of Team Rocket (sv10)", era: "SCARLET & VIOLET ERA", aliases: ["Glory Of Team Rocket"] },
  { label: "Hot Air Arena (sv9a)", era: "SCARLET & VIOLET ERA", aliases: ["Hot Air Arena"] },
  { label: "Battle Partners (sv9)", era: "SCARLET & VIOLET ERA", aliases: ["Battle Partners"] },
  { label: "Terastal Festival ex (sv8a)", era: "SCARLET & VIOLET ERA", aliases: ["Terastal Festival Ex"] },
  { label: "Super Electric Breaker (sv8)", era: "SCARLET & VIOLET ERA", aliases: ["Super Electric Breaker"] },
  { label: "Paradise Dragona (sv7a)", era: "SCARLET & VIOLET ERA", aliases: ["Paradise Dragona"] },
  { label: "Stellar Miracle (sv7)", era: "SCARLET & VIOLET ERA", aliases: ["Stellar Miracle"] },
  { label: "Night Wanderer (sv6a)", era: "SCARLET & VIOLET ERA", aliases: ["Night Wanderer"] },
  { label: "Mask of Change (sv6)", era: "SCARLET & VIOLET ERA", aliases: ["Mask Of Change"] },
  { label: "Crimson Haze (sv5a)", era: "SCARLET & VIOLET ERA", aliases: ["Crimson Haze"] },
  { label: "Cyber Judge (sv5M)", era: "SCARLET & VIOLET ERA", aliases: ["Cyber Judge"] },
  { label: "Wild Force (sv5K)", era: "SCARLET & VIOLET ERA", aliases: ["Wild Force"] },
  { label: "Shiny Treasure ex (sv4a)", era: "SCARLET & VIOLET ERA", aliases: ["Shiny Treasure Ex"] },
  { label: "Future Flash (sv4M)", era: "SCARLET & VIOLET ERA", aliases: ["Future Flash"] },
  { label: "Ancient Roar (sv4K)", era: "SCARLET & VIOLET ERA", aliases: ["Ancient Roar"] },
  { label: "Raging Surf (sv3a)", era: "SCARLET & VIOLET ERA", aliases: ["Raging Surf"] },
  { label: "Ruler of the Black Flame (sv3)", era: "SCARLET & VIOLET ERA", aliases: ["Ruler Of The Black", "Ruler Of The Black Flame"] },
  { label: "Pokemon Card 151 Japanese (sv2a)", era: "SCARLET & VIOLET ERA", aliases: ["Pokemon Card 151 Japanese", "Pokemon Card 151"] },
  { label: "Clay Burst (sv2D)", era: "SCARLET & VIOLET ERA", aliases: ["Clay Burst"] },
  { label: "Snow Hazard (sv2P)", era: "SCARLET & VIOLET ERA", aliases: ["Snow Hazard"] },
  { label: "Triplet Beat (sv1a)", era: "SCARLET & VIOLET ERA", aliases: ["Triplet Beat"] },
  { label: "Violet ex (sv1V)", era: "SCARLET & VIOLET ERA", aliases: ["Violet Ex"] },
  { label: "Scarlet ex (sv1S)", era: "SCARLET & VIOLET ERA", aliases: ["Scarlet Ex"] },
  { label: "SV-P Promos", era: "SCARLET & VIOLET ERA", aliases: ["Sv P Promos", "SV-P Promos"] },
  { label: "Trading Card Game Classic Japanese Blastoise", era: "SWORD & SHIELD ERA", aliases: ["Trading Card Game Classic Japanese Blastoise"] },
  { label: "Trading Card Game Classic Japanese Venusaur", era: "SWORD & SHIELD ERA", aliases: ["Trading Card Game Classic Japanese Venusaur"] },
  { label: "Trading Card Game Classic Japanese Charizard", era: "SWORD & SHIELD ERA", aliases: ["Trading Card Game Classic Japanese Charizard"] },
  { label: "VSTAR Universe (s12a)", era: "SWORD & SHIELD ERA", aliases: ["Vstar Universe"] },
  { label: "Paradigm Trigger (s12)", era: "SWORD & SHIELD ERA", aliases: ["Paradigm Trigger"] },
  { label: "Incandescent Arcana (s11a)", era: "SWORD & SHIELD ERA", aliases: ["Incandescent Arcana"] },
  { label: "VSTAR Special Set (sp6)", era: "SWORD & SHIELD ERA", aliases: ["Vstar Special Set"] },
  { label: "Lost Abyss (s11)", era: "SWORD & SHIELD ERA", aliases: ["Lost Abyss"] },
  { label: "Deoxys VSTAR & VMAX High-Class Deck (sPD)", era: "SWORD & SHIELD ERA", aliases: ["Deoxys Vstar Vmax High Class Deck", "Deoxys VSTAR & VMAX High-Class Deck"] },
  { label: "Zeraora VSTAR & VMAX High-Class Deck (sPZ)", era: "SWORD & SHIELD ERA", aliases: ["Zeraora Vstar Vmax High Class Deck", "Zeraora VSTAR & VMAX High-Class Deck"] },
  { label: "Pokemon GO Japanese (s10B)", era: "SWORD & SHIELD ERA", aliases: ["Pokemon Go Japanese", "Pokemon Go"] },
  { label: "Dark Phantasma (s10A)", era: "SWORD & SHIELD ERA", aliases: ["Dark Phantasma"] },
  { label: "Space Juggler (s10P)", era: "SWORD & SHIELD ERA", aliases: ["Space Juggler"] },
  { label: "Time Gazer (s10D)", era: "SWORD & SHIELD ERA", aliases: ["Time Gazer"] },
  { label: "Darkrai VSTAR Starter Set (sLD)", era: "SWORD & SHIELD ERA", aliases: ["Darkrai Vstar Starter Set"] },
  { label: "Lucario VSTAR Starter Set (sLL)", era: "SWORD & SHIELD ERA", aliases: ["Lucario Vstar Starter Set"] },
  { label: "Battle Region (s9A)", era: "SWORD & SHIELD ERA", aliases: ["Battle Region"] },
  { label: "Start Deck 100 CoroCoro Comic Version (sN)", era: "SWORD & SHIELD ERA", aliases: ["Start Deck 100 Corocoro Comic Version"] },
  { label: "VSTAR Premium Trainer Box (sK)", era: "SWORD & SHIELD ERA", aliases: ["Vstar Premium Trainer Box"] },
  { label: "Star Birth (s9)", era: "SWORD & SHIELD ERA", aliases: ["Star Birth"] },
  { label: "Start Deck 100 (sI)", era: "SWORD & SHIELD ERA", aliases: ["Start Deck 100"] },
  { label: "VMAX Climax (s8B)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Climax"] },
  { label: "Zacian & Zamazenta vs Eternatus Special Deck Set (sJ)", era: "SWORD & SHIELD ERA", aliases: ["Zacian Zamazenta Vs Eternatus Special Deck Set"] },
  { label: "25th Anniversary Golden Box (s8a-G)", era: "SWORD & SHIELD ERA", aliases: ["25th Anniversary Golden Box"] },
  { label: "25th Anniversary Collection (s8A)", era: "SWORD & SHIELD ERA", aliases: ["25th Anniversary Collection"] },
  { label: "Promo Card Pack 25th Anniversary Edition (s8a-P)", era: "SWORD & SHIELD ERA", aliases: ["Promo Card Pack 25th Anniversary Edition"] },
  { label: "Fusion Arts (s8)", era: "SWORD & SHIELD ERA", aliases: ["Fusion Arts"] },
  { label: "V-UNION Special Card Sets (sp5)", era: "SWORD & SHIELD ERA", aliases: ["V Union Special Card Sets"] },
  { label: "Sword & Shield Family Pokémon Card Game (sH)", era: "SWORD & SHIELD ERA", aliases: ["Sword Shield Family Pokemon Card Game"] },
  { label: "Towering Perfection (s7D)", era: "SWORD & SHIELD ERA", aliases: ["Towering Perfection"] },
  { label: "Blue Sky Stream (s7R)", era: "SWORD & SHIELD ERA", aliases: ["Blue Sky Stream"] },
  { label: "Eevee Heroes VMAX Special Set (sp4)", era: "SWORD & SHIELD ERA", aliases: ["Eevee Heroes Vmax Special Set"] },
  { label: "Eevee Heroes (s6A)", era: "SWORD & SHIELD ERA", aliases: ["Eevee Heroes"] },
  { label: "Gengar VMAX High-Class Deck (sGG)", era: "SWORD & SHIELD ERA", aliases: ["Gengar Vmax High Class Deck"] },
  { label: "Inteleon VMAX High-Class Deck (sGI)", era: "SWORD & SHIELD ERA", aliases: ["Inteleon Vmax High Class Deck"] },
  { label: "Silver Lance & Jet-Black Spirit Jumbo Pack Set (sp3)", era: "SWORD & SHIELD ERA", aliases: ["Silver Lance Jet Black Spirit Jumbo Pack Set"] },
  { label: "Jet Black Spirit (s6K)", era: "SWORD & SHIELD ERA", aliases: ["Jet Black Spirit"] },
  { label: "Silver Lance (s6H)", era: "SWORD & SHIELD ERA", aliases: ["Silver Lance"] },
  { label: "Matchless Fighter (s5A)", era: "SWORD & SHIELD ERA", aliases: ["Matchless Fighter"] },
  { label: "Single Strike & Rapid Strike Premium Trainer Boxes (sF)", era: "SWORD & SHIELD ERA", aliases: ["Single Strike Rapid Strike Premium Trainer Boxes"] },
  { label: "Single Strike Master (s5I)", era: "SWORD & SHIELD ERA", aliases: ["Single Strike Master"] },
  { label: "Rapid Strike Master (s5R)", era: "SWORD & SHIELD ERA", aliases: ["Rapid Strike Master"] },
  { label: "VMAX Starter Set (Blastoise) (sEK)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Starter Set Blastoise"] },
  { label: "VMAX Starter Set 2 (Charizard) (sC2)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Starter Set 2 Charizard"] },
  { label: "VMAX Starter Set (Venusaur) (sEF)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Starter Set Venusaur"] },
  { label: "VMAX Special Set (sp2)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Special Set"] },
  { label: "Shiny Star V s4A (s4A)", era: "SWORD & SHIELD ERA", aliases: ["Shiny Star V S4a", "Shiny Star V"] },
  { label: "Astonishing Volt Tackle (s4)", era: "SWORD & SHIELD ERA", aliases: ["Astonishing Volt Tackle"] },
  { label: "Legendary Heartbeat (s3A)", era: "SWORD & SHIELD ERA", aliases: ["Legendary Heartbeat"] },
  { label: "V Starter Decks (sD)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Decks"] },
  { label: "Infinity Zone (s3)", era: "SWORD & SHIELD ERA", aliases: ["Infinity Zone"] },
  { label: "Explosive Walker (s2A)", era: "SWORD & SHIELD ERA", aliases: ["Explosive Walker"] },
  { label: "VMAX Starter Set (Charizard) (sC)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Starter Set Charizard"] },
  { label: "VMAX Starter Set (Grimmsnarl) (sC)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Starter Set Grimmsnarl"] },
  { label: "Rebellion Crash (s2)", era: "SWORD & SHIELD ERA", aliases: ["Rebellion Crash"] },
  { label: "VMAX Rising (s1A)", era: "SWORD & SHIELD ERA", aliases: ["Vmax Rising"] },
  { label: "Zacian Zamazenta Box (sp1)", era: "SWORD & SHIELD ERA", aliases: ["Zacian Zamazenta Box"] },
  { label: "Sword & Shield Premium Trainer Box (sB)", era: "SWORD & SHIELD ERA", aliases: ["Sword Shield Premium Trainer Box"] },
  { label: "Shield (s1H)", era: "SWORD & SHIELD ERA", aliases: ["Shield"] },
  { label: "Sword (s1W)", era: "SWORD & SHIELD ERA", aliases: ["Sword"] },
  { label: "V Starter Set (Fighting) (sA)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Set Fighting"] },
  { label: "V Starter Set (Fire) (sA)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Set Fire"] },
  { label: "V Starter Set (Lightning) (sA)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Set Lightning"] },
  { label: "V Starter Set (Water) (sA)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Set Water"] },
  { label: "V Starter Set (Grass) (sA)", era: "SWORD & SHIELD ERA", aliases: ["V Starter Set Grass"] },
  { label: "S-P Promos", era: "SWORD & SHIELD ERA", aliases: ["S P Promos", "S-P Promos"] },
  { label: "Tag Team GX All Stars (sm12A)", era: "SUN & MOON ERA", aliases: ["Tag Team Gx All Stars"] },
  { label: "Alter Genesis (sm12)", era: "SUN & MOON ERA", aliases: ["Alter Genesis"] },
  { label: "Dream League (sm11B)", era: "SUN & MOON ERA", aliases: ["Dream League"] },
  { label: "Remix Bout (sm11A)", era: "SUN & MOON ERA", aliases: ["Remix Bout"] },
  { label: "Miracle Twin (sm11)", era: "SUN & MOON ERA", aliases: ["Miracle Twin"] },
  { label: "Tag Team GX Starter Sets (smM)", era: "SUN & MOON ERA", aliases: ["Tag Team Gx Starter Sets"] },
  { label: "Great Detective Pikachu (smP2)", era: "SUN & MOON ERA", aliases: ["Great Detective Pikachu"] },
  { label: "Sky Legend (sm10B)", era: "SUN & MOON ERA", aliases: ["Sky Legend"] },
  { label: "GG End (sm10A)", era: "SUN & MOON ERA", aliases: ["Gg End"] },
  { label: "Sun & Moon Family Box (smL)", era: "SUN & MOON ERA", aliases: ["Sun Moon Family Box"] },
  { label: "Double Blaze (sm10)", era: "SUN & MOON ERA", aliases: ["Double Blaze"] },
  { label: "Tag Team GX Deck Build Box (smN)", era: "SUN & MOON ERA", aliases: ["Tag Team Gx Deck Build Box"] },
  { label: "Full Metal Wall (sm9B)", era: "SUN & MOON ERA", aliases: ["Full Metal Wall"] },
  { label: "Trainer Battle Decks (smK)", era: "SUN & MOON ERA", aliases: ["Trainer Battle Decks"] },
  { label: "Night Unison (sm9A)", era: "SUN & MOON ERA", aliases: ["Night Unison"] },
  { label: "Tag Bolt (sm9)", era: "SUN & MOON ERA", aliases: ["Tag Bolt"] },
  { label: "Tag Team GX Premium Trainer Box (smJ)", era: "SUN & MOON ERA", aliases: ["Tag Team Gx Premium Trainer Box"] },
  { label: "Flareon-GX, Vaporeon-GX & Jolteon-GX Starter Sets (smI)", era: "SUN & MOON ERA", aliases: ["Flareon Gx Vaporeon Gx Jolteon Gx Starter Sets"] },
  { label: "GX Ultra Shiny (sm8B)", era: "SUN & MOON ERA", aliases: ["Gx Ultra Shiny"] },
  { label: "Dark Order (sm8A)", era: "SUN & MOON ERA", aliases: ["Dark Order"] },
  { label: "Explosive Impact (sm8)", era: "SUN & MOON ERA", aliases: ["Explosive Impact"] },
  { label: "Fairy Rise (sm7B)", era: "SUN & MOON ERA", aliases: ["Fairy Rise"] },
  { label: "GX Starter Decks (smH)", era: "SUN & MOON ERA", aliases: ["Gx Starter Decks"] },
  { label: "Thunderclap Spark (sm7A)", era: "SUN & MOON ERA", aliases: ["Thunderclap Spark"] },
  { label: "Charisma of the Cracked Sky (sm7)", era: "SUN & MOON ERA", aliases: ["Charisma Of The Cracked Sky"] },
  { label: "Dragon Storm (sm6A)", era: "SUN & MOON ERA", aliases: ["Dragon Storm"] },
  { label: "Champion Road (sm6B)", era: "SUN & MOON ERA", aliases: ["Champion Road"] },
  { label: "Forbidden Light Japanese (sm6)", era: "SUN & MOON ERA", aliases: ["Forbidden Light Japanese", "Forbidden Light Jp"] },
  { label: "Ultra Sun & Ultra Moon Deck Build Boxes (smG)", era: "SUN & MOON ERA", aliases: ["Ultra Sun Ultra Moon Deck Build Boxes"] },
  { label: "Ultra Force (sm5+)", era: "SUN & MOON ERA", aliases: ["Ultra Force"] },
  { label: "Ultra Sun & Ultra Moon Premium Trainer Box (smF)", era: "SUN & MOON ERA", aliases: ["Ultra Sun Ultra Moon Premium Trainer Box"] },
  { label: "Ultra Sun (sm5S)", era: "SUN & MOON ERA", aliases: ["Ultra Sun"] },
  { label: "Ultra Moon (sm5M)", era: "SUN & MOON ERA", aliases: ["Ultra Moon"] },
  { label: "Solgaleo-GX & Lunala-GX Legendary Starter Set (smE)", era: "SUN & MOON ERA", aliases: ["Solgaleo Gx Lunala Gx Legendary Starter Set"] },
  { label: "GX Battle Boost (sm4+)", era: "SUN & MOON ERA", aliases: ["Gx Battle Boost"] },
  { label: "Awakened Heroes (sm4S)", era: "SUN & MOON ERA", aliases: ["Awakened Heroes"] },
  { label: "Transdimensional Beast (sm4A)", era: "SUN & MOON ERA", aliases: ["Transdimensional Beast"] },
  { label: "Shining Legends Japanese (sm3+)", era: "SUN & MOON ERA", aliases: ["Shining Legends Japanese", "Shining Legends Jp"] },
  { label: "Seen the Rainbow Battle (sm3H)", era: "SUN & MOON ERA", aliases: ["Seen The Rainbow Battle"] },
  { label: "Light Consuming Darkness (sm3N)", era: "SUN & MOON ERA", aliases: ["Light Consuming Darkness"] },
  { label: "The Best of XY (XY)", era: "SUN & MOON ERA", aliases: ["The Best Of Xy"] },
  { label: "Facing a New Trial (sm2+)", era: "SUN & MOON ERA", aliases: ["Facing A New Trial"] },
  { label: "Ash vs Team Rocket Deck Kit (smD)", era: "SUN & MOON ERA", aliases: ["Ash Vs Team Rocket Deck Kit"] },
  { label: "Tapu Bulu-GX Enhanced Starter Set (smC)", era: "SUN & MOON ERA", aliases: ["Tapu Bulu Gx Enhanced Starter Set"] },
  { label: "Islands Await You (sm2K)", era: "SUN & MOON ERA", aliases: ["Islands Await You"] },
  { label: "Alolan Moonlight (sm2L)", era: "SUN & MOON ERA", aliases: ["Alolan Moonlight"] },
  { label: "Strength Expansion Pack Sun & Moon (sm1+)", era: "SUN & MOON ERA", aliases: ["Strength Expansion Pack Sun Moon"] },
  { label: "Rockruff Full Power Deck (smP1)", era: "SUN & MOON ERA", aliases: ["Rockruff Full Power Deck"] },
  { label: "Collection Moon (sm1M)", era: "SUN & MOON ERA", aliases: ["Collection Moon"] },
  { label: "Sun & Moon Starter Set (smA)", era: "SUN & MOON ERA", aliases: ["Sun Moon Starter Set"] },
  { label: "Collection Sun (sm1S)", era: "SUN & MOON ERA", aliases: ["Collection Sun"] },
  { label: "Premium Trainer Box (smB)", era: "SUN & MOON ERA", aliases: ["Premium Trainer Box"] },
  { label: "SM-P Promos", era: "SUN & MOON ERA", aliases: ["Sm P Promos", "SM-P Promos"] },
  { label: "Pikachu's New Friends (sm0)", era: "XY ERA", aliases: ["Pikachu S New Friends"] },
  { label: "Expansion Pack 20th Anniversary (CP6)", era: "XY ERA", aliases: ["Expansion Pack 20th Anniversary"] },
  { label: "Mythical & Legendary Dream Shine Collection (CP5)", era: "XY ERA", aliases: ["Mythical Legendary Dream Shine Collection"] },
  { label: "Fever-Burst Fighter (XY11)", era: "XY ERA", aliases: ["Fever Burst Fighter"] },
  { label: "Cruel Traitor (XY11)", era: "XY ERA", aliases: ["Cruel Traitor"] },
  { label: "Awakening Psychic King (XY10)", era: "XY ERA", aliases: ["Awakening Psychic King"] },
  { label: "Zygarde-EX Perfect Battle Deck (XYg)", era: "XY ERA", aliases: ["Zygarde Ex Perfect Battle Deck"] },
  { label: "M Audino-EX Mega Battle Deck (XYh)", era: "XY ERA", aliases: ["M Audino Ex Mega Battle Deck"] },
  { label: "Premium Champion Pack (CP4)", era: "XY ERA", aliases: ["Premium Champion Pack"] },
  { label: "BREAK Starter Pack (20th)", era: "XY ERA", aliases: ["Break Starter Pack 20th"] },
  { label: "PokéKyun Collection (CP3)", era: "XY ERA", aliases: ["Pokekyun Collection"] },
  { label: "Rage of the Broken Heavens (XY9)", era: "XY ERA", aliases: ["Rage Of The Broken Heavens"] },
  { label: "Golduck BREAK Palkia-EX Combo Deck (XYf)", era: "XY ERA", aliases: ["Golduck Break Palkia Ex Combo Deck"] },
  { label: "Red Flash (XY8)", era: "XY ERA", aliases: ["Red Flash"] },
  { label: "Raichu BREAK Evolution Pack (SNP)", era: "XY ERA", aliases: ["Raichu Break Evolution Pack"] },
  { label: "Blue Shock (XY8)", era: "XY ERA", aliases: ["Blue Shock"] },
  { label: "Noivern BREAK Evolution Pack (SNP)", era: "XY ERA", aliases: ["Noivern Break Evolution Pack"] },
  { label: "M Master Deck Build Box Power Style (MMB)", era: "XY ERA", aliases: ["M Master Deck Build Box Power Style"] },
  { label: "Legendary Shine Collection (CP2)", era: "XY ERA", aliases: ["Legendary Shine Collection"] },
  { label: "Emboar-EX vs Togekiss-EX Deck Kit (XYe)", era: "XY ERA", aliases: ["Emboar Ex Vs Togekiss Ex Deck Kit"] },
  { label: "Bandit Ring (XY7)", era: "XY ERA", aliases: ["Bandit Ring"] },
  { label: "Emerald Break (XY6)", era: "XY ERA", aliases: ["Emerald Break"] },
  { label: "M Rayquaza-EX Mega Battle Deck (XYd)", era: "XY ERA", aliases: ["M Rayquaza Ex Mega Battle Deck"] },
  { label: "Magma Gang vs Aqua Gang: Double Crisis (CP1)", era: "XY ERA", aliases: ["Magma Gang Vs Aqua Gang Double Crisis"] },
  { label: "Gaia Volcano (XY5)", era: "XY ERA", aliases: ["Gaia Volcano"] },
  { label: "Tidal Storm (XY5)", era: "XY ERA", aliases: ["Tidal Storm"] },
  { label: "Xerneas-EX & Yveltal-EX Super Legend Set (XYc)", era: "XY ERA", aliases: ["Xerneas Ex Yveltal Ex Super Legend Set"] },
  { label: "Phantom Gate (XY4)", era: "XY ERA", aliases: ["Phantom Gate"] },
  { label: "Dialga-EX Aegislash-EX Hyper Metal Chain Deck (XYb)", era: "XY ERA", aliases: ["Dialga Ex Aegislash Ex Hyper Metal Chain Deck"] },
  { label: "Rising Fist (XY3)", era: "XY ERA", aliases: ["Rising Fist"] },
  { label: "Wild Blaze (XY2)", era: "XY ERA", aliases: ["Wild Blaze"] },
  { label: "M Charizard-EX Mega Battle Deck (XYa)", era: "XY ERA", aliases: ["M Charizard Ex Mega Battle Deck"] },
  { label: "Yveltal Half Deck (Y30)", era: "XY ERA", aliases: ["Yveltal Half Deck"] },
  { label: "Xerneas Half Deck (X30)", era: "XY ERA", aliases: ["Xerneas Half Deck"] },
  { label: "Pokemon Scrap", era: "XY ERA", aliases: ["Pokemon Scrap"] },
  { label: "Collection X (XY1)", era: "XY ERA", aliases: ["Collection X"] },
  { label: "Collection Y (XY1)", era: "XY ERA", aliases: ["Collection Y"] },
  { label: "XY Beginning Set (HXY)", era: "XY ERA", aliases: ["Xy Beginning Set"] },
  { label: "XY Promos", era: "XY ERA", aliases: ["Xy Promos"] },
  { label: "EX Battle Boost (EBB)", era: "BLACK & WHITE ERA", aliases: ["EX Battle Boost"] },
  { label: "Mewtwo vs Genesect Deck Kit (Mewtwo) (MG)", era: "BLACK & WHITE ERA", aliases: ["Mewtwo vs Genesect Deck Kit (Mewtwo)", "Mewtwo vs Genesect Deck Kit Mewtwo"] },
  { label: "Mewtwo vs Genesect Deck Kit (Genesect) (MG)", era: "BLACK & WHITE ERA", aliases: ["Mewtwo vs Genesect Deck Kit (Genesect)", "Mewtwo vs Genesect Deck Kit Genesect"] },
  { label: "Blastoise Kyurem-EX Combo Deck (K+K)", era: "BLACK & WHITE ERA", aliases: ["Blastoise Kyurem-EX Combo Deck"] },
  { label: "Megalo Cannon (BW9)", era: "BLACK & WHITE ERA", aliases: ["Megalo Cannon"] },
  { label: "Shiny Collection (SC)", era: "BLACK & WHITE ERA", aliases: ["Shiny Collection"] },
  { label: "Spiral Force (BW8)", era: "BLACK & WHITE ERA", aliases: ["Spiral Force"] },
  { label: "Thunder Knuckle (BW8)", era: "BLACK & WHITE ERA", aliases: ["Thunder Knuckle"] },
  { label: "Team Plasma Battle Gift Set (PBG)", era: "BLACK & WHITE ERA", aliases: ["Team Plasma Battle Gift Set"] },
  { label: "Everyone's Exciting Battle (WAK)", era: "BLACK & WHITE ERA", aliases: ["Everyone's Exciting Battle"] },
  { label: "Black Kyurem-EX Battle Strength Deck (BKB)", era: "BLACK & WHITE ERA", aliases: ["Black Kyurem-EX Battle Strength Deck"] },
  { label: "White Kyurem-EX Battle Strength Deck (BKW)", era: "BLACK & WHITE ERA", aliases: ["White Kyurem-EX Battle Strength Deck"] },
  { label: "Master Deck Build Box EX (MDB)", era: "BLACK & WHITE ERA", aliases: ["Master Deck Build Box EX"] },
  { label: "Plasma Gale (BW7)", era: "BLACK & WHITE ERA", aliases: ["Plasma Gale"] },
  { label: "Team Plasma Powered Half Deck (PPD)", era: "BLACK & WHITE ERA", aliases: ["Team Plasma Powered Half Deck"] },
  { label: "Freeze Bolt (BW6)", era: "BLACK & WHITE ERA", aliases: ["Freeze Bolt"] },
  { label: "Cold Flare (BW6)", era: "BLACK & WHITE ERA", aliases: ["Cold Flare"] },
  { label: "Keldeo Battle Strength Deck (KLD)", era: "BLACK & WHITE ERA", aliases: ["Keldeo Battle Strength Deck"] },
  { label: "National Pokedex Beginning Set (HSZ)", era: "BLACK & WHITE ERA", aliases: ["National Pokedex Beginning Set"] },
  { label: "Garchomp Half Deck (GBR)", era: "BLACK & WHITE ERA", aliases: ["Garchomp Half Deck"] },
  { label: "Dragon Blast (BW5)", era: "BLACK & WHITE ERA", aliases: ["Dragon Blast"] },
  { label: "Dragon Blade (BW5)", era: "BLACK & WHITE ERA", aliases: ["Dragon Blade"] },
  { label: "Hydreigon Half Deck (SZD)", era: "BLACK & WHITE ERA", aliases: ["Hydreigon Half Deck"] },
  { label: "Dragon Selection (DS)", era: "BLACK & WHITE ERA", aliases: ["Dragon Selection"] },
  { label: "Dark Rush (BW4)", era: "BLACK & WHITE ERA", aliases: ["Dark Rush"] },
  { label: "Beginning Set Pikachu (Oshawott) (HSP)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Pikachu (Oshawott)"] },
  { label: "Beginning Set Pikachu (Tepig) (HSP)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Pikachu (Tepig)"] },
  { label: "Thundurus vs Tornadus Battle Gift Set (BGS)", era: "BLACK & WHITE ERA", aliases: ["Thundurus vs Tornadus Battle Gift Set"] },
  { label: "Beginning Set Pikachu (Snivy) (HSP)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Pikachu (Snivy)"] },
  { label: "Zekrom-EX Battle Strength Deck (BKZ)", era: "BLACK & WHITE ERA", aliases: ["Zekrom-EX Battle Strength Deck"] },
  { label: "Reshiram-EX Battle Strength Deck (BKR)", era: "BLACK & WHITE ERA", aliases: ["Reshiram-EX Battle Strength Deck"] },
  { label: "Hail Blizzard (BW3)", era: "BLACK & WHITE ERA", aliases: ["Hail Blizzard"] },
  { label: "Psycho Drive (BW3)", era: "BLACK & WHITE ERA", aliases: ["Psycho Drive"] },
  { label: "Beginning Set Plus (Snivy) (HS+)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Plus (Snivy)"] },
  { label: "Beginning Set Plus (Tepig) (HS+)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Plus (Tepig)"] },
  { label: "Beginning Set Plus (Oshawott) (HS+)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set Plus (Oshawott)"] },
  { label: "Red Collection (BW2)", era: "BLACK & WHITE ERA", aliases: ["Red Collection"] },
  { label: "Victini Battle Theme Deck (BTV)", era: "BLACK & WHITE ERA", aliases: ["Victini Battle Theme Deck"] },
  { label: "Terrakion Battle Strength Deck (BK)", era: "BLACK & WHITE ERA", aliases: ["Terrakion Battle Strength Deck"] },
  { label: "Cobalion Battle Strength Deck (BK)", era: "BLACK & WHITE ERA", aliases: ["Cobalion Battle Strength Deck"] },
  { label: "Virizion Battle Strength Deck (BK)", era: "BLACK & WHITE ERA", aliases: ["Virizion Battle Strength Deck"] },
  { label: "White Collection (BW1)", era: "BLACK & WHITE ERA", aliases: ["White Collection"] },
  { label: "Black Collection (BW1)", era: "BLACK & WHITE ERA", aliases: ["Black Collection"] },
  { label: "Black & White Promos", era: "BLACK & WHITE ERA", aliases: ["Black & White Promos"] },
  { label: "Beginning Set (Snivy) (HS)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set (Snivy)"] },
  { label: "Beginning Set (Oshawott) (HS)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set (Oshawott)"] },
  { label: "Beginning Set (Tepig) (HS)", era: "BLACK & WHITE ERA", aliases: ["Beginning Set (Tepig)"] },
  { label: "Journey Partners (CS1)", era: "BLACK & WHITE ERA", aliases: ["Journey Partners"] },
  { label: "Clash at the Summit (L3)", era: "LEGEND ERA", aliases: ["Clash at the Summit"] },
  { label: "Lost Link (LL)", era: "LEGEND ERA", aliases: ["Lost Link"] },
  { label: "Tyranitar Constructed Standard Deck (L2)", era: "LEGEND ERA", aliases: ["Tyranitar Constructed Standard Deck"] },
  { label: "Reviving Legends (L2)", era: "LEGEND ERA", aliases: ["Reviving Legends"] },
  { label: "Steelix Constructed Standard Deck (L2)", era: "LEGEND ERA", aliases: ["Steelix Constructed Standard Deck"] },
  { label: "Battle Starter Deck (Torterra) (B)", era: "LEGEND ERA", aliases: ["Battle Starter Deck (Torterra)"] },
  { label: "Leafeon VS Metagross Expert Deck Online (E)", era: "LEGEND ERA", aliases: ["Leafeon VS Metagross Expert Deck Online"] },
  { label: "Battle Starter Deck (Raichu) (B)", era: "LEGEND ERA", aliases: ["Battle Starter Deck (Raichu)"] },
  { label: "Battle Starter Deck (Blastoise) (B)", era: "LEGEND ERA", aliases: ["Battle Starter Deck (Blastoise)"] },
  { label: "Battle Starter Deck (Magmortar) (B)", era: "LEGEND ERA", aliases: ["Battle Starter Deck (Magmortar)"] },
  { label: "HeartGold Collection (L1)", era: "LEGEND ERA", aliases: ["HeartGold Collection"] },
  { label: "SoulSilver Collection (L1)", era: "LEGEND ERA", aliases: ["SoulSilver Collection"] },
  { label: "LEGEND Promos", era: "LEGEND ERA", aliases: ["LEGEND Promos"] },
  { label: "Movie Commemoration Random Pack (M)", era: "PLATINUM ERA", aliases: ["Movie Commemoration Random Pack"] },
  { label: "Melee! Pok?mon Scramble (L)", era: "PLATINUM ERA", aliases: ["Melee! Pok?mon Scramble", "Melee! Pokemon Scramble"] },
  { label: "Arceus LV.X Deck (Grass & Fire) (Pt)", era: "PLATINUM ERA", aliases: ["Arceus LV.X Deck (Grass & Fire)"] },
  { label: "Advent of Arceus (pt4)", era: "PLATINUM ERA", aliases: ["Advent of Arceus"] },
  { label: "Arceus LV.X Deck (Lightning & Psychic) (Pt)", era: "PLATINUM ERA", aliases: ["Arceus LV.X Deck (Lightning & Psychic)"] },
  { label: "Collection Pack (Mewtwo LV.X) (PtM)", era: "PLATINUM ERA", aliases: ["Collection Pack (Mewtwo LV.X)"] },
  { label: "Collection Pack (Regigigas LV.X) (PtR)", era: "PLATINUM ERA", aliases: ["Collection Pack (Regigigas LV.X)"] },
  { label: "Collection Pack (Shaymin LV.X) (PtS)", era: "PLATINUM ERA", aliases: ["Collection Pack (Shaymin LV.X)"] },
  { label: "Charizard Half Deck 2009 (Pt)", era: "PLATINUM ERA", aliases: ["Charizard Half Deck 2009"] },
  { label: "Garchomp Half Deck 2009 (Pt)", era: "PLATINUM ERA", aliases: ["Garchomp Half Deck 2009"] },
  { label: "Beat of the Frontier (Pt3)", era: "PLATINUM ERA", aliases: ["Beat of the Frontier"] },
  { label: "SP Deck Kit (Infernape) (Pt)", era: "PLATINUM ERA", aliases: ["SP Deck Kit (Infernape)"] },
  { label: "Bonds to the End of Time (Pt2)", era: "PLATINUM ERA", aliases: ["Bonds to the End of Time"] },
  { label: "SP Deck Kit (Gallade) (Pt)", era: "PLATINUM ERA", aliases: ["SP Deck Kit (Gallade)"] },
  { label: "DPt Gift Box (Turtwig) (Pt)", era: "PLATINUM ERA", aliases: ["DPt Gift Box (Turtwig)"] },
  { label: "DPt Gift Box (Pikachu) (Pt)", era: "PLATINUM ERA", aliases: ["DPt Gift Box (Pikachu)"] },
  { label: "DPt Gift Box (Chimchar) (Pt)", era: "PLATINUM ERA", aliases: ["DPt Gift Box (Chimchar)"] },
  { label: "DPt Gift Box (Piplup) (Pt)", era: "PLATINUM ERA", aliases: ["DPt Gift Box (Piplup)"] },
  { label: "Giratina Half Deck", era: "PLATINUM ERA", aliases: ["Giratina Half Deck"] },
  { label: "Dialga Half Deck", era: "PLATINUM ERA", aliases: ["Dialga Half Deck"] },
  { label: "Palkia Half Deck", era: "PLATINUM ERA", aliases: ["Palkia Half Deck"] },
  { label: "Galactic's Conquest (Pt1)", era: "PLATINUM ERA", aliases: ["Galactic's Conquest"] },
  { label: "DPt-P Promos", era: "PLATINUM ERA", aliases: ["DPt-P Promos"] },
  { label: "11th Movie Commemoration Set", era: "DIAMOND & PEARL ERA", aliases: ["11th Movie Commemoration Set"] },
  { label: "Intense Fight in the Destroyed Sky", era: "DIAMOND & PEARL ERA", aliases: ["Intense Fight in the Destroyed Sky"] },
  { label: "Cry From The Mysterious (DP5)", era: "DIAMOND & PEARL ERA", aliases: ["Cry From The Mysterious"] },
  { label: "Temple of Anger (DP5)", era: "DIAMOND & PEARL ERA", aliases: ["Temple of Anger"] },
  { label: "Heatran Half Deck (DP5)", era: "DIAMOND & PEARL ERA", aliases: ["Heatran Half Deck"] },
  { label: "Regigigas Half Deck (DP5)", era: "DIAMOND & PEARL ERA", aliases: ["Regigigas Half Deck"] },
  { label: "Torterra Half Deck 2007", era: "DIAMOND & PEARL ERA", aliases: ["Torterra Half Deck 2007"] },
  { label: "Raichu Half Deck 2007", era: "DIAMOND & PEARL ERA", aliases: ["Raichu Half Deck 2007"] },
  { label: "Empoleon Half Deck 2007", era: "DIAMOND & PEARL ERA", aliases: ["Empoleon Half Deck 2007"] },
  { label: "Infernape Half Deck 2007", era: "DIAMOND & PEARL ERA", aliases: ["Infernape Half Deck 2007"] },
  { label: "Electivire Half Deck (DP4)", era: "DIAMOND & PEARL ERA", aliases: ["Electivire Half Deck"] },
  { label: "Moonlit Pursuit (DP4)", era: "DIAMOND & PEARL ERA", aliases: ["Moonlit Pursuit"] },
  { label: "Magmortar Half Deck (DP4)", era: "DIAMOND & PEARL ERA", aliases: ["Magmortar Half Deck"] },
  { label: "Dawn Dash (DP4)", era: "DIAMOND & PEARL ERA", aliases: ["Dawn Dash"] },
  { label: "10th Movie Commemoration Set (10th)", era: "DIAMOND & PEARL ERA", aliases: ["10th Movie Commemoration Set"] },
  { label: "World Champions Pack", era: "DIAMOND & PEARL ERA", aliases: ["World Champions Pack"] },
  { label: "Dialga LV.X Constructed Standard Deck (DP3)", era: "DIAMOND & PEARL ERA", aliases: ["Dialga LV.X Constructed Standard Deck"] },
  { label: "Shining Darkness (DP3)", era: "DIAMOND & PEARL ERA", aliases: ["Shining Darkness"] },
  { label: "Palkia LV.X Constructed Standard Deck (DP3)", era: "DIAMOND & PEARL ERA", aliases: ["Palkia LV.X Constructed Standard Deck"] },
  { label: "PPP Promos", era: "DIAMOND & PEARL ERA", aliases: ["PPP Promos"] },
  { label: "Rampardos the Attacker (DP2)", era: "DIAMOND & PEARL ERA", aliases: ["Rampardos the Attacker"] },
  { label: "Bastiodon the Defender (DP2)", era: "DIAMOND & PEARL ERA", aliases: ["Bastiodon the Defender"] },
  { label: "Secret of the Lakes (DP2)", era: "DIAMOND & PEARL ERA", aliases: ["Secret of the Lakes"] },
  { label: "DP-P Promos", era: "DIAMOND & PEARL ERA", aliases: ["DP-P Promos"] },
  { label: "Space-Time Creation (DP1)", era: "DIAMOND & PEARL ERA", aliases: ["Space-Time Creation"] },
  { label: "Torterra Half Deck 2006 (DP)", era: "DIAMOND & PEARL ERA", aliases: ["Torterra Half Deck 2006"] },
  { label: "Empoleon Half Deck 2006 (DP)", era: "DIAMOND & PEARL ERA", aliases: ["Empoleon Half Deck 2006"] },
  { label: "Infernape Half Deck 2006 (DP)", era: "DIAMOND & PEARL ERA", aliases: ["Infernape Half Deck 2006"] },
  { label: "Mightyena Quarter Deck", era: "DIAMOND & PEARL ERA", aliases: ["Mightyena Quarter Deck"] },
  { label: "Crawdaunt Quarter Deck", era: "DIAMOND & PEARL ERA", aliases: ["Crawdaunt Quarter Deck"] },
  { label: "Mew Quarter Deck", era: "DIAMOND & PEARL ERA", aliases: ["Mew Quarter Deck"] },
  { label: "Lucario Quarter Deck", era: "DIAMOND & PEARL ERA", aliases: ["Lucario Quarter Deck"] },
  { label: "Shockwave Tyranitar Constructed Standard Deck", era: "PCG ERA", aliases: ["Shockwave Tyranitar Constructed Standard Deck"] },
  { label: "Imprison Gardevoir Constructed Deck", era: "PCG ERA", aliases: ["Imprison Gardevoir Constructed Deck"] },
  { label: "Movie Commemoration VS Pack Sea's Manaphy (Vs)", era: "PCG ERA", aliases: ["Movie Commemoration VS Pack Sea's Manaphy"] },
  { label: "Offense and Defense of the Furthest Ends", era: "PCG ERA", aliases: ["Offense and Defense of the Furthest Ends"] },
  { label: "Miracle Crystal", era: "PCG ERA", aliases: ["Miracle Crystal"] },
  { label: "Earth's Groudon Constructed Starter Deck", era: "PCG ERA", aliases: ["Earth's Groudon Constructed Starter Deck"] },
  { label: "Ocean's Kyogre Constructed Starter Deck", era: "PCG ERA", aliases: ["Ocean's Kyogre Constructed Starter Deck"] },
  { label: "Holon Phantom", era: "PCG ERA", aliases: ["Holon Phantom"] },
  { label: "Holon Research Tower", era: "PCG ERA", aliases: ["Holon Research Tower"] },
  { label: "Rocket Gang Strikes Back (R)", era: "PCG ERA", aliases: ["Rocket Gang Strikes Back"] },
  { label: "Holon Research Tower Water Quarter Deck", era: "PCG ERA", aliases: ["Holon Research Tower Water Quarter Deck"] },
  { label: "Holon Research Tower: Fire Quarter Deck", era: "PCG ERA", aliases: ["Holon Research Tower: Fire Quarter Deck"] },
  { label: "Holon Research Tower Lightning Quarter Deck", era: "PCG ERA", aliases: ["Holon Research Tower Lightning Quarter Deck"] },
  { label: "Mirage Forest", era: "PCG ERA", aliases: ["Mirage Forest"] },
  { label: "Movie Commemoration VS Pack Aura's Lucario (Vs)", era: "PCG ERA", aliases: ["Movie Commemoration VS Pack Aura's Lucario"] },
  { label: "Torchic Quarter Deck", era: "PCG ERA", aliases: ["Torchic Quarter Deck"] },
  { label: "Side Deck", era: "PCG ERA", aliases: ["Side Deck"] },
  { label: "Bulbasaur Quarter Deck", era: "PCG ERA", aliases: ["Bulbasaur Quarter Deck"] },
  { label: "Mirage's Mew Constructed Starter Deck", era: "PCG ERA", aliases: ["Mirage's Mew Constructed Starter Deck"] },
  { label: "Golden Sky, Silvery Ocean", era: "PCG ERA", aliases: ["Golden Sky, Silvery Ocean"] },
  { label: "Pok?Park Blue", era: "PCG ERA", aliases: ["Pok?Park Blue", "PokePark Blue"] },
  { label: "Pok?Park Forest", era: "PCG ERA", aliases: ["Pok?Park Forest", "PokePark Forest"] },
  { label: "Feraligatr Constructed Starter Deck", era: "PCG ERA", aliases: ["Feraligatr Constructed Starter Deck"] },
  { label: "Typhlosion Constructed Starter Deck", era: "PCG ERA", aliases: ["Typhlosion Constructed Starter Deck"] },
  { label: "Meganium Constructed Starter Deck", era: "PCG ERA", aliases: ["Meganium Constructed Starter Deck"] },
  { label: "Grass Quick Construction Pack", era: "PCG ERA", aliases: ["Grass Quick Construction Pack"] },
  { label: "Fire Quick Construction Pack", era: "PCG ERA", aliases: ["Fire Quick Construction Pack"] },
  { label: "Water Quick Construction Pack", era: "PCG ERA", aliases: ["Water Quick Construction Pack"] },
  { label: "Fighting Quick Construction Pack", era: "PCG ERA", aliases: ["Fighting Quick Construction Pack"] },
  { label: "Psychic Quick Construction Pack", era: "PCG ERA", aliases: ["Psychic Quick Construction Pack"] },
  { label: "Lightning Quick Construction Pack", era: "PCG ERA", aliases: ["Lightning Quick Construction Pack"] },
  { label: "Deoxys Half Deck", era: "PCG ERA", aliases: ["Deoxys Half Deck"] },
  { label: "Rayquaza Half Deck", era: "PCG ERA", aliases: ["Rayquaza Half Deck"] },
  { label: "Black Deck Kit", era: "PCG ERA", aliases: ["Black Deck Kit"] },
  { label: "Movie Commemoration VS Pack: Sky-Splitting Deoxys (Vs)", era: "PCG ERA", aliases: ["Movie Commemoration VS Pack: Sky-Splitting Deoxys", "Movie Commemoration VS Pack Sky-Splitting Deoxys"] },
  { label: "Deoxys Starter Deck", era: "PCG ERA", aliases: ["Deoxys Starter Deck"] },
  { label: "Rayquaza Starter Deck", era: "PCG ERA", aliases: ["Rayquaza Starter Deck"] },
  { label: "Clash of the Blue Sky", era: "PCG ERA", aliases: ["Clash of the Blue Sky"] },
  { label: "Flight of Legends", era: "PCG ERA", aliases: ["Flight of Legends"] },
  { label: "Charizard Starter Deck", era: "PCG ERA", aliases: ["Charizard Starter Deck"] },
  { label: "Venusaur Starter Deck", era: "PCG ERA", aliases: ["Venusaur Starter Deck"] },
  { label: "Blastoise Starter Deck", era: "PCG ERA", aliases: ["Blastoise Starter Deck"] },
  { label: "PCG-P Promos", era: "PCG ERA", aliases: ["PCG-P Promos"] },
  { label: "Undone Seal", era: "ADV ERA", aliases: ["Undone Seal"] },
  { label: "Magma vs Aqua: Two Ambitions", era: "ADV ERA", aliases: ["Magma vs Aqua: Two Ambitions"] },
  { label: "Rulers of the Heavens", era: "ADV ERA", aliases: ["Rulers of the Heavens"] },
  { label: "Miracle of the Desert", era: "ADV ERA", aliases: ["Miracle of the Desert"] },
  { label: "ADV Expansion Pack", era: "ADV ERA", aliases: ["ADV Expansion Pack"] },
  { label: "PLAY Promos", era: "ADV ERA", aliases: ["PLAY Promos"] },
  { label: "ADV-P Promos", era: "ADV ERA", aliases: ["ADV-P Promos"] },
  { label: "Mysterious Mountains", era: "e-CARD ERA", aliases: ["Mysterious Mountains"] },
  { label: "Split Earth", era: "e-CARD ERA", aliases: ["Split Earth"] },
  { label: "Wind from the Sea", era: "e-CARD ERA", aliases: ["Wind from the Sea"] },
  { label: "The Town on No Map", era: "e-CARD ERA", aliases: ["The Town on No Map"] },
  { label: "McDonald's Pok?mon-e Minimum Pack", era: "e-CARD ERA", aliases: ["McDonald's Pok?mon-e Minimum Pack", "McDonald's Pokemon-e Minimum Pack"] },
  { label: "T Promos", era: "e-CARD ERA", aliases: ["T Promos"] },
  { label: "Base Expansion Pack", era: "e-CARD ERA", aliases: ["Base Expansion Pack"] },
  { label: "J Promos", era: "e-CARD ERA", aliases: ["J Promos"] },
  { label: "P Promos", era: "e-CARD ERA", aliases: ["P Promos"] },
  { label: "Pok?mon Web", era: "WEB & VS ERA", aliases: ["Pok?mon Web", "Pokemon Web"] },
  { label: "Pok?mon VS", era: "WEB & VS ERA", aliases: ["Pok?mon VS", "Pokemon VS"] },
  { label: "Darkness, and to Light...", era: "NEO ERA", aliases: ["Darkness, and to Light..."] },
  { label: "Intro Pack Neo (Chikorita)", era: "NEO ERA", aliases: ["Intro Pack Neo"] },
  { label: "Intro Pack Neo (Totodile)", era: "NEO ERA", aliases: ["Intro Pack Neo"] },
  { label: "Awakening Legends", era: "NEO ERA", aliases: ["Awakening Legends"] },
  { label: "Crossing the Ruins...", era: "NEO ERA", aliases: ["Crossing the Ruins..."] },
  { label: "Gold, Silver, to a New World...", era: "NEO ERA", aliases: ["Gold, Silver, to a New World..."] },
  { label: "Intro Pack (Bulbasaur)", era: "ORIGINAL ERA", aliases: ["Intro Pack"] },
  { label: "Intro Pack (Squirtle)", era: "ORIGINAL ERA", aliases: ["Intro Pack"] },
  { label: "Southern Islands Japanese", era: "ORIGINAL ERA", aliases: ["Southern Islands Japanese"] },
  { label: "Challenge from the Darkness", era: "ORIGINAL ERA", aliases: ["Challenge from the Darkness"] },
  { label: "Yamabuki City Gym Sabrina", era: "ORIGINAL ERA", aliases: ["Yamabuki City Gym Sabrina"] },
  { label: "Vending Machine (Series 3)", era: "ORIGINAL ERA", aliases: ["Vending Machine"] },
  { label: "Leaders' Stadium", era: "ORIGINAL ERA", aliases: ["Leaders' Stadium"] },
  { label: "Kuchiba City Gym Lt. Surge", era: "ORIGINAL ERA", aliases: ["Kuchiba City Gym Lt. Surge"] },
  { label: "Tamamushi City Gym Erika", era: "ORIGINAL ERA", aliases: ["Tamamushi City Gym Erika"] },
  { label: "Vending Machine (Series 2)", era: "ORIGINAL ERA", aliases: ["Vending Machine"] },
  { label: "Hanada City Gym Misty", era: "ORIGINAL ERA", aliases: ["Hanada City Gym Misty"] },
  { label: "Nivi City Gym Brock", era: "ORIGINAL ERA", aliases: ["Nivi City Gym Brock"] },
  { label: "Vending Machine (Series 1)", era: "ORIGINAL ERA", aliases: ["Vending Machine"] },
  { label: "Rocket Gang", era: "ORIGINAL ERA", aliases: ["Rocket Gang"] },
  { label: "Mystery of the Fossils", era: "ORIGINAL ERA", aliases: ["Mystery of the Fossils"] },
  { label: "Pok?mon Jungle", era: "ORIGINAL ERA", aliases: ["Pok?mon Jungle", "Pokemon Jungle"] },
  { label: "Expansion Pack", era: "ORIGINAL ERA", aliases: ["Expansion Pack"] },
  { label: "Unnumbered Promos", era: "ORIGINAL ERA", aliases: ["Unnumbered Promos"] },
];
